### ISSUE TITLE
Test mpf-examples

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#508]
- Demo man integration test has to run with MC. Put on MC side?
- Test tutorial
- Test other machines?

**Comment by toomanybrians** [comment]
delete all the broken examples, keep demo_man, tutorial, and big shot

**Comment by jabdoa2** [comment]
@toomanybrians this should be fixed, right?

**Comment by toomanybrians** [comment]
The build still fails for some reason, but I'll track the issues in that repo and close this one
